name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@db1fb3032d9f9a0a3ad24819e88c1b82fab4231c # main
        with:
          image-name: ubuntu-cloud-archive
          push: ${{ github.event_name != 'pull_request' }}
