name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@2bed598442494c60f1f9ae004626473f7c400bf7 # main
        with:
          image-name: ubuntu-cloud-archive
          push: ${{ github.event_name != 'pull_request' }}
