name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@e012e9b7df8e22166070c4389caf52285807598a # main
        with:
          image-name: ubuntu-cloud-archive
          push: ${{ github.event_name != 'pull_request' }}
