name: periodic

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - zed
          - antelope
          - bobcat
          - caracal
    steps:
      - uses: vexxhost/github-actions/scan-image@main
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/ubuntu-cloud-archive:${{ matrix.release }}
